version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promptlab
    ports:
      - "80:3000"  # Mapear al puerto 80 para acceso directo
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    restart: always
    # Límites ajustados para 1GB RAM
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M  # Dejar algo de RAM para el sistema
        reservations:
          cpus: '0.2'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # Development service (uncomment for local development)
  # dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   image: promptlab:dev
  #   container_name: promptlab-dev
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=development
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   command: npm run dev
  #   networks:
  #     - app_network
  #   profiles:
  #     - dev

networks:
  app_network:
    driver: bridge 